### ISSUE TITLE
LaravelAuth v1.0.0

### ISSUE THREAD

**Issue by arcanedev-maroc** [ARCANEDEV/LaravelAuth#4]
## TODO
- [x] Add user impersonation.
- [x] Add user's `last activity` tracking.
- [x] Add social network authentication compatibility with Socialite.
- [x] Move the `Observers` Folder inside the `Models` Folder.
- [x] Move the `Trait` Folder inside the `Models` Folder.
